local modpath, modname, S = ...

local creative_mode = minetest.settings:get_bool("creative_mode")

assert(loadfile(modpath .. "/api/api_helper_functions.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_datetime.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_spawn.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_orders.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_init_prop.lua"))(modpath, S) --Load the init the properties for the entities
assert(loadfile(modpath .. "/api/api_forms.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_on_rightclick.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_on_die.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_on_punch.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_feed_tame.lua"))(modpath, S, creative_mode)
assert(loadfile(modpath .. "/api/api_capture.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_tamagochi.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_breed.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_wool_milk.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_mount.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_dreamcatcher.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_eggs.lua"))(modpath, S)
--assert(loadfile(modpath .. "/api/api_squareball.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_convert.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_nametag.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_dam_beaver.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_particles.lua"))(modpath, S)
--assert(loadfile(modpath .. "/api/api_whistle.lua"))(modpath, S)
--assert(loadfile(modpath .. "/api/api_silk.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_on_step.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_sleep.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_env_damage.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_bees.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_throw.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_collisionbox.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_colorize.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_horseshoes.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_blood.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_poop.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_brush.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_bottled.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_colors.lua"))(modpath, S)
assert(loadfile(modpath .. "/api/api_sell_buy.lua"))(S)
assert(loadfile(modpath .. "/api/api_lifetime.lua"))(S)
